
CREATE TABLE IF NOT EXISTS `job_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;


INSERT INTO `job_category` (`id`, `name`) VALUES
(1, 'Administrative'),
(2, 'B2B Sales Programs'),
(3, 'Big Data'),
(4, 'Big Data Internships'),
(5, 'Bilingual'),
(6, 'Bilingual Korean'),
(7, 'Bilingual Mandarin'),
(8, 'Bilingual Russian'),
(9, 'Bilingual Spanish'),
(10, 'Bilingual Tagalog'),
(12, 'Bilingual Vietnamese'),
(13, 'Broadcast Operations'),
(14, 'Business Sales Solutions'),
(15, 'Call Center'),
(16, 'College'),
(17, 'Construction'),
(18, 'Consumer Sales'),
(19, 'Content and Entertainment'),
(20, 'Corporate'),
(31, 'Cricket Wireless'),
(32, 'Customer Advocate'),
(33, 'Customer Service'),
(34, 'Customer Support'),
(35, 'Data Science'),
(36, 'Developer'),
(37, 'DIRECTV'),
(38, 'Featured Jobs Corporate'),
(39, 'Field Sales'),
(40, 'Field Services'),
(41, 'Finance'),
(42, 'Finance Internships'),
(43, 'Finance Programs'),
(44, 'Government Support'),
(45, 'Human Resources'),
(46, 'Internships'),
(47, 'IT'),
(48, 'Labs and Research'),
(49, 'Leadership Development Program'),
(50, 'Marketing and PR'),
(51, 'Operations'),
(52, 'Outside Plant Technician'),
(53, 'Part Time'),
(54, 'Product Marketing'),
(55, 'Relay Associate'),
(56, 'Retail'),
(57, 'Retail Management'),
(58, 'Sales'),
(59, 'Software Development'),
(60, 'Software Development Internship'),
(61, 'Software Development Program'),
(62, 'Store Manager'),
(63, 'Technical Planning Engineering'),
(64, 'Technician'),
(65, 'Technology'),
(66, 'Technology Development Internships'),
(67, 'Technology Development Programs'),
(68, 'User Experience'),
(69, 'UX and UI'),
(70, 'Warehouse'),
(71, 'Wire Technician');